//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.IO;
using System.IO.IsolatedStorage;

using Microsoft.Phone.Data.Linq.Mapping;
using Microsoft.Phone.Data.Linq;



[global::System.Data.Linq.Mapping.TableAttribute(Name="tblFabrikat")]
public partial class TblFabrikat : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Bezeichnung;
	
	private EntitySet<TblAuftrag> _TblAuftrag;
	
    #region Definitionen der Extensibility-Methode
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBezeichnungChanging(string value);
    partial void OnBezeichnungChanged();
    #endregion
	
	public TblFabrikat()
	{
		this._TblAuftrag = new EntitySet<TblAuftrag>(new Action<TblAuftrag>(this.attach_TblAuftrag), new Action<TblAuftrag>(this.detach_TblAuftrag));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bezeichnung", DbType="NVarChar(100)")]
	public string Bezeichnung
	{
		get
		{
			return this._Bezeichnung;
		}
		set
		{
			if ((this._Bezeichnung != value))
			{
				this.OnBezeichnungChanging(value);
				this.SendPropertyChanging();
				this._Bezeichnung = value;
				this.SendPropertyChanged("Bezeichnung");
				this.OnBezeichnungChanged();
			}
		}
	}
	
	/*[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_KFZFabrikatNr", Storage="_TblAuftrag", ThisKey="ID", OtherKey="KfzFabrikatNr", DeleteRule="CASCADE")]
	public EntitySet<TblAuftrag> TblAuftrag
	{
		get
		{
			return this._TblAuftrag;
		}
		set
		{
			this._TblAuftrag.Assign(value);
		}
	}*/
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_TblAuftrag(TblAuftrag entity)
	{
		this.SendPropertyChanging();
		entity.TblFabrikat = this;
	}
	
	private void detach_TblAuftrag(TblAuftrag entity)
	{
		this.SendPropertyChanging();
		entity.TblFabrikat = null;
	}
}