//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.IO;
using System.IO.IsolatedStorage;

using Microsoft.Phone.Data.Linq.Mapping;
using Microsoft.Phone.Data.Linq;



[global::System.Data.Linq.Mapping.TableAttribute(Name="tblVersicherung")]
public partial class TblVersicherung : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _VersicherungNr;
	
	private string _Name;
	
	private EntitySet<TblAuftrag> _TblAuftrag;
	
    #region Definitionen der Extensibility-Methode
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVersicherungNrChanging(int value);
    partial void OnVersicherungNrChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
	
	public TblVersicherung()
	{
		this._TblAuftrag = new EntitySet<TblAuftrag>(new Action<TblAuftrag>(this.attach_TblAuftrag), new Action<TblAuftrag>(this.detach_TblAuftrag));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="versicherungNr", Storage="_VersicherungNr", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int VersicherungNr
	{
		get
		{
			return this._VersicherungNr;
		}
		set
		{
			if ((this._VersicherungNr != value))
			{
				this.OnVersicherungNrChanging(value);
				this.SendPropertyChanging();
				this._VersicherungNr = value;
				this.SendPropertyChanged("VersicherungNr");
				this.OnVersicherungNrChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="name", Storage="_Name", DbType="NVarChar(100)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	/*[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_VersicherungNR", Storage="_TblAuftrag", ThisKey="VersicherungNr", OtherKey="VersicherungNr", DeleteRule="CASCADE")]
	public EntitySet<TblAuftrag> TblAuftrag
	{
		get
		{
			return this._TblAuftrag;
		}
		set
		{
			this._TblAuftrag.Assign(value);
		}
	}*/
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_TblAuftrag(TblAuftrag entity)
	{
		this.SendPropertyChanging();
		entity.TblVersicherung = this;
	}
	
	private void detach_TblAuftrag(TblAuftrag entity)
	{
		this.SendPropertyChanging();
		entity.TblVersicherung = null;
	}
}