//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.IO;
using System.IO.IsolatedStorage;

using Microsoft.Phone.Data.Linq.Mapping;
using Microsoft.Phone.Data.Linq;



[global::System.Data.Linq.Mapping.TableAttribute(Name="tblAttachment")]
public partial class TblAttachment : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _AttachmentNr;
	
	private System.Nullable<int> _Typ;
	
	private string _Data;
	
	private EntitySet<TblAuftrag> _TblAuftrag;
	
    #region Definitionen der Extensibility-Methode
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAttachmentNrChanging(int value);
    partial void OnAttachmentNrChanged();
    partial void OnTypChanging(System.Nullable<int> value);
    partial void OnTypChanged();
    partial void OnDataChanging(string value);
    partial void OnDataChanged();
    #endregion
	
	public TblAttachment()
	{
		this._TblAuftrag = new EntitySet<TblAuftrag>(new Action<TblAuftrag>(this.attach_TblAuftrag), new Action<TblAuftrag>(this.detach_TblAuftrag));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="attachmentNr", Storage="_AttachmentNr", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int AttachmentNr
	{
		get
		{
			return this._AttachmentNr;
		}
		set
		{
			if ((this._AttachmentNr != value))
			{
				this.OnAttachmentNrChanging(value);
				this.SendPropertyChanging();
				this._AttachmentNr = value;
				this.SendPropertyChanged("AttachmentNr");
				this.OnAttachmentNrChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="typ", Storage="_Typ", DbType="Int")]
	public System.Nullable<int> Typ
	{
		get
		{
			return this._Typ;
		}
		set
		{
			if ((this._Typ != value))
			{
				this.OnTypChanging(value);
				this.SendPropertyChanging();
				this._Typ = value;
				this.SendPropertyChanged("Typ");
				this.OnTypChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data", Storage="_Data", DbType="NVarChar(100)")]
	public string Data
	{
		get
		{
			return this._Data;
		}
		set
		{
			if ((this._Data != value))
			{
				this.OnDataChanging(value);
				this.SendPropertyChanging();
				this._Data = value;
				this.SendPropertyChanged("Data");
				this.OnDataChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_AttachmentNr", Storage="_TblAuftrag", ThisKey="AttachmentNr", OtherKey="AttachmentNr", DeleteRule="CASCADE")]
	public EntitySet<TblAuftrag> TblAuftrag
	{
		get
		{
			return this._TblAuftrag;
		}
		set
		{
			this._TblAuftrag.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_TblAuftrag(TblAuftrag entity)
	{
		this.SendPropertyChanging();
		entity.TblAttachment = this;
	}
	
	private void detach_TblAuftrag(TblAuftrag entity)
	{
		this.SendPropertyChanging();
		entity.TblAttachment = null;
	}
}